services:
  - type: web
    name: capstone2-app
    runtime: docker
    plan: free
    dockerContext: "./Capstone 2"
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "10000"
